### ISSUE TITLE
Problem on ted59 zero-shot translation

### ISSUE THREAD

**Issue by zanchangtong** [cordercorder/nmt-multi#5]
Hey, thank you for the released code. 
I tried to first reproduce the baseline Token_src model on the ted59 dataset. The Sacrebleu scores of supervised experiments are consistent with those in the paper, but the zero-shot experiment only achieves 8.87 Bleu (-1.63 Bleu). I select the final model with supervised performance on validation set. 
**Settings:** 
max-tokens=16384, other settings are the same as the released script (nmt-multi/scripts/ted/train/fairseq_train.many-many.token_src.sh). 
![image](https://user-images.githubusercontent.com/41229202/196371946-e25abc80-461d-4319-bd51-beaaaa565ee9.png)

**Comment by cordercorder** [comment]
Hi, thanks for your attention.

As there are no test sets for zero-shot translation on the TED-59 dataset, we construct 3306 (58 * 57) test sets for zero-shot language pairs by pairing sentences of any two languages via aligned English sentences in the original test sets.

Is the test sets you use for zero-shot translation on the TED-59 dataset the same as ours?

**Comment by zanchangtong** [comment]
I use the nmt-multi/scripts/ted/data_process/extract_parallel_data_from_centric_corpus.sh to extract zero-shot test sets from the tokenized parallel corpora, and process them with fairseq-preprocess.

**Comment by zanchangtong** [comment]
Will it be the effect of max-tokens=16384?  The total batch size is 16384*4.

**Comment by cordercorder** [comment]
Yes, we also used this script to produce test sets for zero-shot translation on the TED-59 dataset.

> I use the nmt-multi/scripts/ted/data_process/extract_parallel_data_from_centric_corpus.sh to extract zero-shot test sets from the tokenized parallel corpora, and process them with fairseq-preprocess.


Maybe. I only use max-tokens=4096 throughout the experiments and the total batch size is 65536 (4096 * 4 * 4, max-tokens * num_process * update-freq).

> Will it be the effect of max-tokens=16384? The total batch size is 16384*4.


Do you remove the artificial English tag (\_\_en\_\_) prepended  to every non-English sentence in the raw dataset? This may also affect model training and bias BLEU.

**Comment by zanchangtong** [comment]
Yes, i use nmt-multi/scripts/ted/data_process/remove_start_token.sh before running multilingual_preprocess.sh. And, the supervised translation experiments on bitext corpora are good.

**Comment by cordercorder** [comment]
It seems like that all the procedures run well. Maybe the BLEU score discrepancy is caused by the difference of batch-size.

**Comment by zanchangtong** [comment]
I have tried the setting of max-tokens=4096 with the total batch size not changing. But, it is disappointing that zero-shot performance(8.9078 Bleu) is also significantly lower than the paper reported.

**Comment by zanchangtong** [comment]
Is it convenient to provide the zero-shot test set or bleu results of each zero-shot translation task? Maybe after comparing the intermediate results, I can find out where the bug is. 
Here are the zero-shot bleu results of my model: [zero-shot_8.9bleu_ted59.json.txt](https://github.com/cordercorder/nmt-multi/files/9822378/zero-shot_8.9bleu_ted59.json.txt).

**Comment by cordercorder** [comment]
There are the training script and logs for Token_src on the TED-59 dataset.

[fairseq_train.many-many_4.logs.txt](https://github.com/cordercorder/nmt-multi/files/9822709/fairseq_train.many-many_4.logs.txt)

[fairseq_train.many-many_4.sh.txt](https://github.com/cordercorder/nmt-multi/files/9822700/fairseq_train.many-many_4.sh.txt)

**Comment by cordercorder** [comment]
I also attempt to upload the translation generated by Token_src trained on the TED-59 dataset for you to debug easily. Disappointedly, the file size is beyond the limit of GitHub. (File size too big: 25MB are allowed, 320 MB were attempted to upload)

**Comment by cordercorder** [comment]
I notice that you used the `checkpoint_best.pt` for testing. Did you select the checkpoint according to the loss on the validation sets?

**Comment by zanchangtong** [comment]
I selected the model based on the validation bleu score but got the final zero-shot bleu still below(9.04 BLEU). And, the performance is not influenced by max_tokens=4096 or 8198, when the total batch size does not change.

**Comment by zanchangtong** [comment]
After comparing the training log, I find that my model's validation is higher(4.617 vs 4.482) and my raw dataset size is slightly larger(10109386 vs 10092756). 
Are there some missing data filtering operations? I directly extract parallel data from the ted_talk dataset.
This is the detailed information on dataset size:[raw_data_size.txt](https://github.com/cordercorder/nmt-multi/files/9838958/raw_data_size.txt)

**Comment by cordercorder** [comment]
We only removed the sentences which contains more than 100 sub-words for training sets and validation sets of every language pair. There was no extra filtering operations during data preprocessing. It seems like that there are also some filtering operations in your data preprocessing pipeline (maybe removing long sentences). Can you provide the detailed script for data preprocessing?

> After comparing the training log, I find that my model's validation is higher(4.617 vs 4.482) and my raw dataset size is slightly larger(10109386 vs 10092756). Are there some missing data filtering operations? I directly extract parallel data from the ted_talk dataset. This is the detailed information on dataset size:[raw_data_size.txt](https://github.com/cordercorder/nmt-multi/files/9838958/raw_data_size.txt)

Below are the raw script we used for data preprocessing and the dictionary for all languages involved in TED-59 dataset:
[multilingual_preprocess.sh.txt](https://github.com/cordercorder/nmt-multi/files/9840654/multilingual_preprocess.sh.txt)
[dict.txt](https://github.com/cordercorder/nmt-multi/files/9840671/dict.txt)

**Comment by cordercorder** [comment]
I find that there is only one small difference between our data preprocessing pipeline after comparing our scripts for corpus generation and preprocessing. I used the python script `ted_reader.py` in this [repository](https://github.com/neulab/word-embeddings-for-nmt) to read the parallel corpus of XX -> En from the raw TED-59 dataset. After that, I copied the parallel corpus of XX -> En into the reverse direction to construct the parallel corpus of EN -> XX. In comparison, it seems like you used the python script `ted_reader.py` to construct the parallel corpus of both XX -> En and En -> XX directions. Can you check whether the parallel corpus of EN -> XX is identical to its inverse direction (XX -> En)?

In addition, as the raw TED-59 dataset has been tokenized by [Moses](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/tokenizer/tokenizer.perl) and detokenized input is required by [sacreBLEU](https://github.com/mjpost/sacrebleu), the translation and reference need to be detokenized before computing the BLEU score. Did you detokenize the translation and reference? If convenient, could you provide the detailed scripts for computing the BLEU score?

**Comment by zanchangtong** [comment]
I checked my training data according to the sample number and content. The EN -> XX data is identical to its inverse direction (XX -> En). 
For evaluation, I perform detokenize with sacremoses for references and system outputs. Here is my evaluation script.
[report_bleu.zero-shot.txt](https://github.com/cordercorder/nmt-multi/files/9866654/report_bleu.zero-shot.txt)

**Comment by zanchangtong** [comment]
I find that the batch size(bsz) in my experiments is a little larger than your training log reported, and my training loss(loss) is also larger. For example, 
```
2022-10-18 15:27:22 | INFO | train_inner | epoch 001:    103 / 7544 loss=15.456, nll_loss=15.317, ppl=40833.8, wps=180950, ups=3.43, wpb=52723.9, bsz=1972.6, num_updates=100, lr=1.25975e-05, gnorm=2.382, loss_scale=16, train_wall=32, gb_free=33.8, wall=58
2022-10-18 15:27:47 | INFO | train_inner | epoch 001:    203 / 7544 loss=13.933, nll_loss=13.627, ppl=12652.3, wps=208537, ups=3.91, wpb=53367.6, bsz=2019.5, num_updates=200, lr=2.5095e-05, gnorm=1.159, loss_scale=16, train_wall=23, gb_free=33.9, wall=84
2022-10-18 15:28:12 | INFO | train_inner | epoch 001:    303 / 7544 loss=12.626, nll_loss=12.15, ppl=4544.26, wps=216561, ups=4.02, wpb=53823.8, bsz=2004.4, num_updates=300, lr=3.75925e-05, gnorm=1.044, loss_scale=16, train_wall=22, gb_free=33.8, wall=108
```
Compared with yours: 
```
2021-07-10 01:02:23 | INFO | train_inner | epoch 001:    103 / 8110 loss=15.282, nll_loss=15.123, ppl=35686.6, wps=52429.6, ups=1.01, wpb=51871.2, bsz=1828.1, num_updates=100, lr=1.25975e-05, gnorm=2.562, loss_scale=16, train_wall=100, gb_free=4.7, wall=176
2021-07-10 01:04:00 | INFO | train_inner | epoch 001:    203 / 8110 loss=13.381, nll_loss=13.001, ppl=8199.27, wps=53128.7, ups=1.02, wpb=52000.2, bsz=1848.1, num_updates=200, lr=2.5095e-05, gnorm=1.145, loss_scale=16, train_wall=91, gb_free=4.8, wall=274
2021-07-10 01:05:38 | INFO | train_inner | epoch 001:    303 / 8110 loss=11.968, nll_loss=11.401, ppl=2703.35, wps=53723.3, ups=1.03, wpb=52318.6, bsz=1913.9, num_updates=300, lr=3.75925e-05, gnorm=0.945, loss_scale=16, train_wall=89, gb_free=4.7, wall=371
```
It is a little weird about the difference in batch size with the same max-token setting. When I reduce the max-token to keep the same batch size, the loss is reduced while also larger than yours:
```
2022-10-26 04:56:48 | INFO | train_inner | epoch 001:    103 / 8208 loss=15.335, nll_loss=15.181, ppl=37155.5, wps=198170, ups=4.06, wpb=48780.4, bsz=1842.2, num_updates=100, lr=1.25975e-05, gnorm=2.359, loss_scale=16, train_wall=27, gb_free=34.1, wall=47
2022-10-26 04:57:10 | INFO | train_inner | epoch 001:    203 / 8208 loss=13.841, nll_loss=13.522, ppl=11763, wps=222517, ups=4.51, wpb=49321, bsz=1887, num_updates=200, lr=2.5095e-05, gnorm=1.125, loss_scale=16, train_wall=20, gb_free=34.1, wall=69
2022-10-26 04:57:32 | INFO | train_inner | epoch 001:    303 / 8208 loss=12.52, nll_loss=12.028, ppl=4174.92, wps=221221, ups=4.55, wpb=48591.5, bsz=1832.9, num_updates=300, lr=3.75925e-05, gnorm=0.939, loss_scale=16, train_wall=20, gb_free=34.1, wall=91
```

**Comment by cordercorder** [comment]
Thanks for your checking. The evaluation script seems well.

> I checked my training data according to the sample number and content. The EN -> XX data is identical to its inverse direction (XX -> En). For evaluation, I perform detokenize with sacremoses for references and system outputs. Here is my evaluation script. [report_bleu.zero-shot.txt](https://github.com/cordercorder/nmt-multi/files/9866654/report_bleu.zero-shot.txt)


This is strange. Could you check whether the vocabularies we used are the same? I have shared my vocabulary [here](https://github.com/cordercorder/nmt-multi/files/9840671/dict.txt). Besides, which version of fairseq did you use?

> I find that the batch size(bsz) in my experiments is a little larger than your training log reported, and my training loss(loss) is also larger. For example,
> 
> ```
> 2022-10-18 15:27:22 | INFO | train_inner | epoch 001:    103 / 7544 loss=15.456, nll_loss=15.317, ppl=40833.8, wps=180950, ups=3.43, wpb=52723.9, bsz=1972.6, num_updates=100, lr=1.25975e-05, gnorm=2.382, loss_scale=16, train_wall=32, gb_free=33.8, wall=58
> 2022-10-18 15:27:47 | INFO | train_inner | epoch 001:    203 / 7544 loss=13.933, nll_loss=13.627, ppl=12652.3, wps=208537, ups=3.91, wpb=53367.6, bsz=2019.5, num_updates=200, lr=2.5095e-05, gnorm=1.159, loss_scale=16, train_wall=23, gb_free=33.9, wall=84
> 2022-10-18 15:28:12 | INFO | train_inner | epoch 001:    303 / 7544 loss=12.626, nll_loss=12.15, ppl=4544.26, wps=216561, ups=4.02, wpb=53823.8, bsz=2004.4, num_updates=300, lr=3.75925e-05, gnorm=1.044, loss_scale=16, train_wall=22, gb_free=33.8, wall=108
> ```
> 
> Compared with yours:
> 
> ```
> 2021-07-10 01:02:23 | INFO | train_inner | epoch 001:    103 / 8110 loss=15.282, nll_loss=15.123, ppl=35686.6, wps=52429.6, ups=1.01, wpb=51871.2, bsz=1828.1, num_updates=100, lr=1.25975e-05, gnorm=2.562, loss_scale=16, train_wall=100, gb_free=4.7, wall=176
> 2021-07-10 01:04:00 | INFO | train_inner | epoch 001:    203 / 8110 loss=13.381, nll_loss=13.001, ppl=8199.27, wps=53128.7, ups=1.02, wpb=52000.2, bsz=1848.1, num_updates=200, lr=2.5095e-05, gnorm=1.145, loss_scale=16, train_wall=91, gb_free=4.8, wall=274
> 2021-07-10 01:05:38 | INFO | train_inner | epoch 001:    303 / 8110 loss=11.968, nll_loss=11.401, ppl=2703.35, wps=53723.3, ups=1.03, wpb=52318.6, bsz=1913.9, num_updates=300, lr=3.75925e-05, gnorm=0.945, loss_scale=16, train_wall=89, gb_free=4.7, wall=371
> ```
> 
> It is a little weird about the difference in batch size with the same max-token setting. When I reduce the max-token to keep the same batch size, the loss is reduced while also larger than yours:
> 
> ```
> 2022-10-26 04:56:48 | INFO | train_inner | epoch 001:    103 / 8208 loss=15.335, nll_loss=15.181, ppl=37155.5, wps=198170, ups=4.06, wpb=48780.4, bsz=1842.2, num_updates=100, lr=1.25975e-05, gnorm=2.359, loss_scale=16, train_wall=27, gb_free=34.1, wall=47
> 2022-10-26 04:57:10 | INFO | train_inner | epoch 001:    203 / 8208 loss=13.841, nll_loss=13.522, ppl=11763, wps=222517, ups=4.51, wpb=49321, bsz=1887, num_updates=200, lr=2.5095e-05, gnorm=1.125, loss_scale=16, train_wall=20, gb_free=34.1, wall=69
> 2022-10-26 04:57:32 | INFO | train_inner | epoch 001:    303 / 8208 loss=12.52, nll_loss=12.028, ppl=4174.92, wps=221221, ups=4.55, wpb=48591.5, bsz=1832.9, num_updates=300, lr=3.75925e-05, gnorm=0.939, loss_scale=16, train_wall=20, gb_free=34.1, wall=91
> ```

**Comment by zanchangtong** [comment]
This is my vocabulary, which is the same as you shared. [dict (3).txt](https://github.com/cordercorder/nmt-multi/files/9868254/dict.3.txt)
The commit ID of fairseq is d3890e5. I clone the latest version fairseq, and use "git checkout d3890e5" to change the version.

> Thanks for your checking. The evaluation script seems well.
> 
> > I checked my training data according to the sample number and content. The EN -> XX data is identical to its inverse direction (XX -> En). For evaluation, I perform detokenize with sacremoses for references and system outputs. Here is my evaluation script. [report_bleu.zero-shot.txt](https://github.com/cordercorder/nmt-multi/files/9866654/report_bleu.zero-shot.txt)
> 
> This is strange. Could you check whether the vocabularies we used are the same? I have shared my vocabulary [here](https://github.com/cordercorder/nmt-multi/files/9840671/dict.txt). Besides, which version of fairseq did you use?
> 
> > I find that the batch size(bsz) in my experiments is a little larger than your training log reported, and my training loss(loss) is also larger. For example,
> > ```
> > 2022-10-18 15:27:22 | INFO | train_inner | epoch 001:    103 / 7544 loss=15.456, nll_loss=15.317, ppl=40833.8, wps=180950, ups=3.43, wpb=52723.9, bsz=1972.6, num_updates=100, lr=1.25975e-05, gnorm=2.382, loss_scale=16, train_wall=32, gb_free=33.8, wall=58
> > 2022-10-18 15:27:47 | INFO | train_inner | epoch 001:    203 / 7544 loss=13.933, nll_loss=13.627, ppl=12652.3, wps=208537, ups=3.91, wpb=53367.6, bsz=2019.5, num_updates=200, lr=2.5095e-05, gnorm=1.159, loss_scale=16, train_wall=23, gb_free=33.9, wall=84
> > 2022-10-18 15:28:12 | INFO | train_inner | epoch 001:    303 / 7544 loss=12.626, nll_loss=12.15, ppl=4544.26, wps=216561, ups=4.02, wpb=53823.8, bsz=2004.4, num_updates=300, lr=3.75925e-05, gnorm=1.044, loss_scale=16, train_wall=22, gb_free=33.8, wall=108
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Compared with yours:
> > ```
> > 2021-07-10 01:02:23 | INFO | train_inner | epoch 001:    103 / 8110 loss=15.282, nll_loss=15.123, ppl=35686.6, wps=52429.6, ups=1.01, wpb=51871.2, bsz=1828.1, num_updates=100, lr=1.25975e-05, gnorm=2.562, loss_scale=16, train_wall=100, gb_free=4.7, wall=176
> > 2021-07-10 01:04:00 | INFO | train_inner | epoch 001:    203 / 8110 loss=13.381, nll_loss=13.001, ppl=8199.27, wps=53128.7, ups=1.02, wpb=52000.2, bsz=1848.1, num_updates=200, lr=2.5095e-05, gnorm=1.145, loss_scale=16, train_wall=91, gb_free=4.8, wall=274
> > 2021-07-10 01:05:38 | INFO | train_inner | epoch 001:    303 / 8110 loss=11.968, nll_loss=11.401, ppl=2703.35, wps=53723.3, ups=1.03, wpb=52318.6, bsz=1913.9, num_updates=300, lr=3.75925e-05, gnorm=0.945, loss_scale=16, train_wall=89, gb_free=4.7, wall=371
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It is a little weird about the difference in batch size with the same max-token setting. When I reduce the max-token to keep the same batch size, the loss is reduced while also larger than yours:
> > ```
> > 2022-10-26 04:56:48 | INFO | train_inner | epoch 001:    103 / 8208 loss=15.335, nll_loss=15.181, ppl=37155.5, wps=198170, ups=4.06, wpb=48780.4, bsz=1842.2, num_updates=100, lr=1.25975e-05, gnorm=2.359, loss_scale=16, train_wall=27, gb_free=34.1, wall=47
> > 2022-10-26 04:57:10 | INFO | train_inner | epoch 001:    203 / 8208 loss=13.841, nll_loss=13.522, ppl=11763, wps=222517, ups=4.51, wpb=49321, bsz=1887, num_updates=200, lr=2.5095e-05, gnorm=1.125, loss_scale=16, train_wall=20, gb_free=34.1, wall=69
> > 2022-10-26 04:57:32 | INFO | train_inner | epoch 001:    303 / 8208 loss=12.52, nll_loss=12.028, ppl=4174.92, wps=221221, ups=4.55, wpb=48591.5, bsz=1832.9, num_updates=300, lr=3.75925e-05, gnorm=0.939, loss_scale=16, train_wall=20, gb_free=34.1, wall=91
> > ```

**Comment by cordercorder** [comment]
As the vocabulary is constructed based on the corpus after applying long sentence filtering operations, the same vocabulary (same 1-gram and its frequency) may indicate that our training sets are also identical. However, it seems like there are more sentences in your training sets according to your previous reply:

> After comparing the training log, I find that my model's validation is higher(4.617 vs 4.482) and my raw dataset size is slightly larger(10109386 vs 10092756). Are there some missing data filtering operations? I directly extract parallel data from the ted_talk dataset. This is the detailed information on dataset size:[raw_data_size.txt](https://github.com/cordercorder/nmt-multi/files/9838958/raw_data_size.txt)


I can not figure out the underline reasons behind these issues based on existing information, such as the performance gap of zero-shot translation on the TED-59 dataset, the difference in training sets size and batch size, and the slightly higher loss during training and validation. Can we communicate through Wechat or QQ for more details?

**Comment by altctrl00** [comment]
I wonder what is the cause of this difference, my raw dataset size is also 10109386, my validation loss is also above 4.6 and BLEU on zero-shot is 9.63

**Comment by zanchangtong** [comment]
Hi, I reduce the training batch size ( be the same as bsz value in the training log) with max-token=3900. Then, I got the zero-shot translation Bleu 10.38 which is much close to the paper report value. So, I think the possible reason for the performance drop may be the difference between actual batch sizes.

**Comment by zanchangtong** [comment]
> Maybe there is some difference between our datasets (including training sets, validation sets, and test sets). I will share them through Baidu Cloud Disk tomorrow (I have to report the research progress to my advisor today).

Thanks, Looking forward to the data you share.
