### ISSUE TITLE
some problem when run ted/train/fairseq_train.many-many.laa.sh

### ISSUE THREAD

**Issue by MildSummerday** [cordercorder/nmt-multi#6]
When I run the script in `ted/train/fairseq_train.many-many.laa.sh`, I get the following error message:
```
File "~/nmt-multi/nmt/user_dir/models/transformer_laa.py", line 460, in forward_scriptable
    tgt_lang_id = tgt_lang_id.squeeze(1) - 1
AttributeError: 'NoneType' object has no attribute 'squeeze' 
```
`tgt_lang_id` appears to be None. How can I solve this problem? Is there something I missed during preprocessing?

**Comment by cordercorder** [comment]
Thanks for reporting this issue. I found that some hyper-parameters were incorrectly set in `ted/train/fairseq_train.many-many.laa.sh`, which was caused during the code clean-up process. I have updated the repository to fix this and the changes can be seen [here](https://github.com/cordercorder/nmt-multi/commit/ee45e95c2a475ada94a36b8f7cbcfc8d22630919). Could you please update the code accordingly and try to run `ted/train/fairseq_train.many-many.laa.sh` again?

**Comment by ghost** [comment]
It works now, thanks!
